name: Add markdown prose labels

on:
  pull_request_target:
    branches: [main]
    types: [labeled,opened,reopened,synchronize]

env:
  GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  add-prose-label:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, vars.LBL_MRKDWNPROSE )) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Verify label exists
        shell: bash
        run: |
          if [[ "${{ vars.LBL_MRKDWNPROSE }}" != $(gh label list --search "${{ vars.LBL_MRKDWNPROSE }}" --json name -q '.[] | .name') ]]; then
            echo "Label ${{ vars.LBL_MRKDWNPROSE }} doesn't exist so I need to create it."
            gh label create "${{ vars.LBL_MRKDWNPROSE }}"
          else
            echo "Label ${{ vars.LBL_MRKDWNPROSE }} already exists so no need to create it."
          fi
      - name: Add prose label
        shell: bash
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ vars.LBL_MRKDWNPROSE }}"

  always-run:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Output event action
        run: |
          echo "The event action is ${{ github.event.action }}"