name: Add markdown prose labels

on:
  pull_request:
    types: [opened,reopened]

env:
  LBL_MRKDWNPROSE: 'markdown/prose'

jobs:
  add-prose-label:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'markdown/prose')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Add prose label
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.LBL_MRKDWNPROSE }}"

