name: Add markdown prose labels

on:
  pull_request:
    types: [opened,reopened]

jobs:
  add-prose-label:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'markdown/prose')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Add prose label
        uses: actions/github-script@v6
        with:
          script: | 
            github.rest.issues.addLabels({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              label: ["markdown/prose"]
            })
